on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: Yarn setup
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 19.4
    
    - name: Build
      run: yarn && yarn build
      
    - name: 'upload'
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: dist

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}
